# Site settings
title: Lifelong Robotic Vision
description: IROS2019 Competition
baseurl: "" 
url: "https://lifelong-robotic-vision.github.io" 

# GitHub User settings
username: Qi She
github_username: lifelong-robotic-vision
user_description: 
user_title: 
email: sheqi1991@gmail.com

# Blog Author settings
author:
  name:           Qi She
  picture:        
  email:          sheqi1991@gmail.com
  description:    
  twitter:
  facebook:
  github:         https://github.com/lifelong-robotic-vision
  linkedin:


# markdown
markdown: kramdown
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 span:
  line_numbers: false
 block:
  line_numbers: true
  start_line: 1
 
highlighter: rouge
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  

permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: true
      highlight: false
      numbering: true
      status: Ongoing
      protected: false
      commentable: true
      rss: true


exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"
 - "*.draft.md"
