# Site settings
title: Welcome
description: A Github Page of Yingkai Liu
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yingkai Liu
user_description: A Physics undergrad with a broad interest
personal_statement: I am interested in the topological properties of materials and the phenomenon of integer discreetness arising from continuous symmetry. In a different perspective, I am interested in how particles subject to relatively simple laws can exhibit to collective novel properties as a whole. I am also a coding enthusiast.
user_title: Physics Undergraduate
email: yingkai.liu@outlook.com

markdown: kramdown

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Categories
    url: /categories
  - title: Tags
    url: /tags

