# Site settings
title: Pointing to the Moon
description: Blog of Yingkai Liu
baseurl: "" 
url: "https://yk-liu.github.io" 

# User settings
username: Yingkai Liu
github_username: yk-liu
user_description: A Physics undergrad with a broad interest
user_title: Physics Undergraduate
email: yingkai.liu@outlook.com

markdown: kramdown
  
kramdown:
 footnote_nr: 1
 entity_output: as_char
 # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
 syntax_highlighter: rouge
 syntax_highlighter_opts:
  # Use existing pygments syntax highlighting css
  css_class: 'highlight'
 
highlighter: rouge

links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Repos
    url: /repo
  - title: Blogs
    url: /blog
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
author:
  name:           Yingkai Liu
  picture:        
  email:          yingkai.liu@outlook.com
  description:    This is a blog for a Physics undergrad with a broad interest. I proudly share my study notes here. 
  twitter:
  facebook:
  github:         https://github.com/yk-liu
  linkedin:


permalink: none

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      toc: true
      mathjax: true
      mermaid: false
      commentable: true
      status: Completed
      protected: false


exclude:
 - LICENSE.md
 - README.md
 - "*.cdf"
 - "*.nb"
 - "*.bk"