# Site settings
title: Welcome
description: A Github Page of Yingkai Liu
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yingkai Liu
user_description: A Physics undergrad with a broad interest
user_title: Physics Undergraduate
email: yingkai.liu@outlook.com

markdown: kramdown
kramdown:
 auto_ids: true
 footnote_nr: 1
 entity_output: as_char


links:
  - title: Home
    url: /
    external: false
    icon: home
  - title: Repos
    url: /repo
  - title: Blogs
    url: /Blog
  - title: Blog Tags
    url: /Blog/Tags
    
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  
author:
  name:           Yingkai Liu
  picture:        
  # email:          
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:    Be Water
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  facebook:
  github: "yk-liu"
  linkedin:
  instagram:
  tumblr:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:

permalink: none