# Site settings
title: Welcome
description: A blog of Yingkai Liu
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: yk liu
user_description: 
user_title: Software Developer
email: yingkai.liu@outlook.com


